name: 🧑‍💻 Update Contributors Automatically

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-contributors:
    runs-on: ubuntu-latest
    name: 🧾 Generate Contributors List

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update Contributors in README
        uses: akhilmhdh/contributors-readme-action@v2.3.11
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: "🧑‍💻 chore: update contributors list"
          image_size: 100
          columns_per_row: 6
          readme_path: "README.md"
          use_username: true
