name: 🧑‍💻 Smart Contributor Updater

on:
  push:
    branches: [ main ]
  pull_request:
    types: [closed]
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"  # run every 1 hour (UTC)

permissions:
  contents: write

jobs:
  update-contributors:
    name: 🧾 Check & Update Contributors
    runs-on: ubuntu-latest

    if: github.event_name != 'pull_request' || github.event.pull_request.merged == true

    steps:
      - name: 🧩 Checkout Repository
        uses: actions/checkout@v4

      - name: 🧠 Get current contributors hash
        id: current
        run: |
          curl -s "https://api.github.com/repos/${{ github.repository }}/contributors?per_page=100" \
          | jq -r '.[].login' | sort > current_contributors.txt
          md5sum current_contributors.txt | cut -d " " -f1 > current_hash.txt
          echo "hash=$(cat current_hash.txt)" >> $GITHUB_OUTPUT

      - name: 📄 Restore previous contributors hash (if exists)
        id: previous
        run: |
          if [ -f .contributors_hash ]; then
            cat .contributors_hash
            echo "hash=$(cat .contributors_hash)" >> $GITHUB_OUTPUT
          else
            echo "hash=none" >> $GITHUB_OUTPUT
          fi

      - name: 🔍 Compare contributor list
        id: compare
        run: |
          if [ "${{ steps.current.outputs.hash }}" = "${{ steps.previous.outputs.hash }}" ]; then
            echo "same=true" >> $GITHUB_OUTPUT
          else
            echo "same=false" >> $GITHUB_OUTPUT
          fi

      - name: ✏️ Update Contributors in README (only if different)
        if: steps.compare.outputs.same == 'false'
        uses: akhilmhdh/contributors-readme-action@v2.3.11
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          readme_path: "README.md"
          image_size: 100
          columns_per_row: 6
          use_username: true
          commit_message: "🧑‍💻 chore: update contributors list"

      - name: 💾 Save new contributor hash
        if: steps.compare.outputs.same == 'false'
        run: |
          cp current_hash.txt .contributors_hash
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Action"
          git add .contributors_hash
          git commit -m "🔄 Update contributors hash" || echo "no changes"
          git push
